### ISSUE TITLE
bold_tax_name Error in CRAN version

### ISSUE THREAD

**Issue by nylander** [ropensci/bold#21]
Dear Scott!

Do you plan push the dev version to CRAN some time soon? Just wondering as bold_tax_name() in CRAN (bold v.0.2.0) has this behavior on some queries not found on boldsystems (see below). The CRAN and github code was restructured so I couldn't spot the bug fast enough (hence this post without a solution):

    > bold_tax_name('Heteroptera')
    Error in `[.data.frame`(data, , vars, drop = FALSE) : 
      undefined columns selected

Compared with (expected):

    > bold_tax_name('Heteropter')
           input
    1 Heteropter
    > bold_tax_name('xHeteroptera')
             input
    1 xHeteroptera
    > bold_tax_name('HeteropteraX')
             input
    1 HeteropteraX

Cheers
Johan

**Comment by sckott** [comment]
@nylander Thanks for your message. It's been a while since a cran push, so I'll try to get it done today.

**Comment by sckott** [comment]
submitted to cran, should be up there soon

**Comment by sckott** [comment]
@nylander
