### ISSUE TITLE
Markers option not working

### ISSUE THREAD

**Issue by boopsboops** [ropensci/bold#25]
A minor bug ... selecting markers has no effect in `bold_seqspec`.
Not such a high priority, as markers other than COI can be discarded manually after the dataframe is downloaded, but took me a while to work out why my sequences would not align!

``` r
unique(bold_seqspec(taxon="Melanogrammus aeglefinus", marker="COI-5P")$markercode)
```

**Comment by sckott** [comment]
thanks, will have a look

**Comment by sckott** [comment]
That's a problem with the BOLD web service. I asked them about it, hopefully we'll get a response soon

**Comment by sckott** [comment]
Seems that this is working now @boopsboops  - make sure to install latest `devtools::install_github("ropensci/bold")`

let me know if not working
