### ISSUE TITLE
dependencies not available

### ISSUE THREAD

**Issue by vanessamata** [ropensci/bold#31]
I'm not being able to install the package in Ubuntu RStudio. I get the following error:

ERROR: dependencies ‘xml2’, ‘reshape’, ‘plyr’ are not available for package ‘bold’

Whenever I try to install these packages individually, I get that they are not available for R version 3.0.2.

Any suggestion?

**Comment by sckott** [comment]
@vanessamata does this mean you solved the problem since you closed the issue?

**Comment by vanessamata** [comment]
yes! after updating my r version I was able to install bold. Apparently when I install r through apt-get it doesn't install the most recent version without some work-around. Thanks!


Date: Tue, 14 Jun 2016 07:39:07 -0700

**Comment by sckott** [comment]
good, glad it works
