### ISSUE TITLE
Database description switcheroo in bold_identify documentation

### ISSUE THREAD

**Issue by dougwyu** [ropensci/bold#37]
The descriptions of these two databases in the documentation for bold_identify() seem to have been switched around, compared to the boldsystems website.

- COX1 Every COI barcode record with a species level identification and a minimum sequence length of 500bp. This includes many species represented by only one or two specimens as well as all species with interim taxonomy.

- COX1_SPECIES Every COI barcode record on BOLD with a minimum sequence length of 500bp (warning: unvalidated library and includes records without species level identification). This includes many species represented by only one or two specimens as well as all species with interim taxonomy. This search only returns a list of the nearest matches and does not provide a probability of placement to a taxon.

**Comment by sckott** [comment]
thanks, I'll have a look

**Comment by sckott** [comment]
fixed
