### ISSUE TITLE
I'm getting the Error: Internal Server Error (HTTP 500) for a small chunk of species names

### ISSUE THREAD

**Issue by tadeu95** [ropensci/bold#74]
<details> <summary><strong>Session Info</strong></summary>

```r
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Portugal.1252  LC_CTYPE=Portuguese_Portugal.1252    LC_MONETARY=Portuguese_Portugal.1252 LC_NUMERIC=C                        
[5] LC_TIME=Portuguese_Portugal.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rentrez_1.2.2     stringr_1.4.0     dplyr_1.0.2       readr_1.3.1       bold_1.1.0        data.table_1.13.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     rstudioapi_0.11  whisker_0.4      xml2_1.3.2       magrittr_1.5     hms_0.5.3        tidyselect_1.1.0 R6_2.4.1         rlang_0.4.7     
[10] fansi_0.4.1      plyr_1.8.6       tools_3.6.1      cli_2.0.2        ellipsis_0.3.1   assertthat_0.2.1 httpcode_0.3.0   tibble_3.0.1     lifecycle_0.2.0 
[19] crayon_1.3.4     purrr_0.3.4      vctrs_0.3.4      triebeard_0.3.0  curl_4.3         crul_0.9.0       glue_1.4.1       stringi_1.4.6    compiler_3.6.1  
[28] pillar_1.4.4     fauxpas_0.5.0    urltools_1.7.3   generics_0.0.2   XML_3.99-0.3     jsonlite_1.6.1   reshape_0.8.8    pkgconfig_2.0.3 
```
</details>

So I've been using the bold_tax_id function and during the past week I was able to successfully use the function for my entire list of species, which comprised about 1300 different species names, without problem. 
![species_taxID_error](https://user-images.githubusercontent.com/52295127/97179995-6bba4b80-1791-11eb-9d5c-95f665850db7.jpg)
However, today I've been trying to use it for a similar species list in size, but I got the "Error: Internal Server Error (HTTP 500)". Since I got the error I began trying to subset the list in smaller chunks but still I am getting the same error even when I try to use the function in chunks of 19 species names (print screen in attachment). Could this be a problem with BOLD's webservice or am I doing something wrong?
Thank you so much in advance.

**Comment by sckott** [comment]
Thanks for the issue @tadeu95  its probably a temporary server problem on BOLD's end, i'll have a look

**Comment by sckott** [comment]
Works fine for me just now. 

Most likely one of two issues. 

1. BOLD was having general server problems for a short time. Just stop requesting and check again later to see if working
2. BOLD may have blocked requests from your IP address if there were "too many" for their liking. There's no way to know if they do this or how many is too many. They don't really respond to questions/inquiries. Same solution as for no. 1, just stop doing requests for a while and check back again later. 

let me know if its still giving that same error when you get a chance to check

**Comment by tadeu95** [comment]
Thanks for the answer.
So I waited for a while and just tried again, but I'm still getting the same error even for a low number of records. Usually when BOLD blocks my IP address it resets after a few minutes and then I'm able to make requests once again, but not this time. 
I'll keep trying and let you know if something more happens

**Comment by dougwyu** [comment]
Try this portal:  https://www.gbif.org/tools/sequence-id

for large datasets, i split my fasta file into sets of 600 sequences.  

it is not command-line driven.

**Comment by tadeu95** [comment]
So I discovered that using the bold_tax_id function, there is a problematic record, its species_taxID is 805613 (the species name is Bathysaurus mollis). 
The function works well except when requesting this particular species. I talked to a coleague and he said this is something that has happened to him with some species/records. 
I removed this ID from my list of species_taxID and I managed to once again request a large number of records.

**Comment by sckott** [comment]
Interesting, that's pretty weird about that one ID.  I would ask BOLD but very unlikely to get a response. I guess you could wrap bold_tax_id in try or tryCatch and  if it gives that error just skip to next, then afterwards see if you can get the missing data in other ways?

**Comment by tadeu95** [comment]
Yes that also sounds like a good idea. Thanks

**Comment by salix-d** [comment]
Another taxon with _supposedly_ no public records ([taxon page](https://v4.boldsystems.org/index.php/Taxbrowser_Taxonpage?taxid=805613) says there is no public record and bold_stats() returns nothing), **BUT** from that same page if you click 'PUBLIC DATA', there _is_ in fact a public record with a sequence...

**Comment by salix-d** [comment]
I did message BOLD just in case they'd be more responsive now and I've been told the devs would take a look so, we'll see.

**Comment by salix-d** [comment]
Turns out, those taxa you can get records of but can't find with `bold_tax_name()` or `bold_tax_id()` might have been flagged in their database, and you may not want to get their records. I just messaged them to let them know that they aren't flag in the Public API and that the records can still be downloaded.

(Which also explains one discrepancy from issue #85)

**Comment by salix-d** [comment]
This function now throws a warning instead of an error and fill the id's row with NA so you won't have to remove those ids.
