### ISSUE TITLE
bold_seqspec ouput contains different vector types between nested lists

### ISSUE THREAD

**Issue by bbvdhoorn** [ropensci/bold#75]
Hi,

When I try to fetch data based on a species list via the code below:

# fetch specimen data and sequences
taxa.list <- c("Asterias rubens", "Ophiura ophiura") # create taxa list
res <- lapply(taxa.list, bold_seqspec) # get specimen data and sequences

the output results in two nested lists/dataframes containing both the same variables/columns, but the type of the columns sometimes differs. When I try to combine the two lists/dataframes in one list or dataframe (e.g. with bind_rows), I get the following errors:
Can't combine `..1$image_ids` <character> and `..2$image_ids` <integer>
Can't combine `..1$copyright_years` <character> and `..2$copyright_years` <integer>

Is this a bug in the output, or am I doing something wrong?

Best,
Berry van der Hoorn

**Comment by sckott** [comment]
Thanks for the issue. Next time please try to include a reproducible example. e.g,. _When I try to combine the two lists/dataframes in one list or dataframe_ should be code

`data.table::rbindlist` works for me, does that work for you?

```r
library(bold)
x <- c("Asterias rubens", "Ophiura ophiura")
res <- lapply(x, bold_seqspec)
data.table::rbindlist(res)
```

**Comment by bbvdhoorn** [comment]
Yes, that works out fine. Thanks! I couldn't have put it that way ;-) Still, I am puzzled that, for example, image_ids is a character in the first nested list and an integer in the second. But your simple line of code solves my issue.

**Comment by sckott** [comment]
> image_ids is a character in the first nested list and an integer in the second

b/c BOLD, like probably all web services can return different data for different records leading to different structures, where one result may be a list with many items and another an empty list. we could internally in this package try to parse all the different fields returned by BOLD, but it's very likely we'll run into errors with certain queries. so i'd rather return data faster, and have users combine data as needed

**Comment by bbvdhoorn** [comment]
I completely agree, thanks again!
